import express from 'express';
import cors from 'cors';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import {fileURLToPath} from 'url';
import 'dotenv/config';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const PORT=process.env.PORT||3000;
const dataDir=path.join(__dirname,'data'); const uploadDir=path.join(__dirname,'uploads');
fs.mkdirSync(dataDir,{recursive:true}); fs.mkdirSync(uploadDir,{recursive:true});
const db=path.join(dataDir,'store.json'); if(!fs.existsSync(db)) fs.writeFileSync(db,JSON.stringify({events:[],orders:[]},null,2));
const read=()=>JSON.parse(fs.readFileSync(db)); const write=x=>fs.writeFileSync(db,JSON.stringify(x,null,2));
app.use(cors()); app.use(express.json()); app.use(express.urlencoded({extended:true})); app.use('/uploads',express.static(uploadDir)); app.use(express.static(path.join(__dirname,'public')));
const upload=multer({dest:uploadDir,limits:{fileSize:50*1024*1024}});
app.get('/api/events',(req,res)=>res.json(read().events));
app.post('/api/events',(req,res)=>{const d=read(); const e={id:Date.now().toString(),name:req.body.name,date:req.body.date,location:req.body.location,price:Number(req.body.price||10),cover:req.body.cover||'',media:[]}; d.events.unshift(e); write(d); res.json(e)});
app.post('/api/events/:id/media',upload.array('files',200),(req,res)=>{const d=read(); const e=d.events.find(x=>x.id===req.params.id); if(!e)return res.status(404).json({error:'Evento não encontrado'}); const items=req.files.map(f=>({id:Date.now()+'-'+f.filename,name:f.originalname,url:'/uploads/'+f.filename,type:f.mimetype.startsWith('video')?'video':'photo',price:Number(req.body.price||e.price)})); e.media.push(...items); write(d); res.json(items)});
app.post('/api/orders',(req,res)=>{const d=read(); const order={id:'GP-'+Date.now(),createdAt:new Date().toISOString(),customer:req.body.customer,items:req.body.items,total:Number(req.body.total||0),status:'pending_pix'}; d.orders.unshift(order); write(d); res.json({order,pix:{status:'demo_pending',message:'Conecte um provedor Pix no servidor para gerar cobrança real.'}})});
app.post('/api/orders/:id/approve',(req,res)=>{const d=read(); const o=d.orders.find(x=>x.id===req.params.id); if(!o)return res.status(404).json({error:'Pedido não encontrado'}); o.status='paid'; write(d); res.json(o)});
app.get('/api/orders/:id',(req,res)=>{const o=read().orders.find(x=>x.id===req.params.id); o?res.json(o):res.status(404).json({error:'Pedido não encontrado'})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`G.P Films em http://localhost:${PORT}`));
